### ISSUE TITLE
Player potential?

### ISSUE THREAD

**Issue by AirRic** [Big-Data-FC/scraper#5]
Hi,

by far I like your scraper the most because it is quite easy to use; however, I am missing the potential value in the output. Is there any way to add it?

Thanks in advance

**Comment by davquar** [comment]
Hello @AirRic 

Yes, you can by taking the value of `pt`, which is already available as you can see from `PLAYERS_BASE_URL`.
Since the Potential is before the 8th column, you must take it manually by defining a remapping [here](https://github.com/Big-Data-FC/scraper/blob/main/src/sofifa/spiders/sofifa.py#L44).

Feel free to add this field and to open a pull request when ready 👍🏼
